### ISSUE TITLE
监听只能在127.0.0.1？

### ISSUE THREAD

**Issue by skyleve** [major1201/dohproxy#5]
win版，设置listen: 0.0.0.0:53，但本地192.168.x.x那种无响应。

另外，一个DNS组里是否能设置多个DNS Sever？
实现同时发起请求，采用最快返回的结果。
或者请求超时能自动请求下一个DNS Sever。
类似下面这种设置：
  CN-Public-DNS:
    type: dns
    address: 119.29.29.29:53
    address: 119.28.28.28:53

**Comment by major1201** [comment]
1. listen 配置的写法参考 README.md 不能直接写 0.0.0.0:53，应该是类似：
```yml
listen:
  - type: udp
    address: 0.0.0.0:53
```

2. 关于 upstream 中设置多个 address 负载均衡，我考虑在后续版本中加上。
